name: 'nuegas'
version: '3.8'
services:
  db:
    container_name: 'nuegas-mongo-db'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    ports:
      - "27017:27017"